#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'
require 'rbconfig'
require 'shellwords'
require 'yaml'

IS_WINDOWS = %w[mswin msys mingw cygwin bccwin wince emc].any?{|s| RbConfig::CONFIG['host_os'].include?(s)}

def convert_bool(str)
  case str.downcase
  when 'yes', 'true'
    true
  when 'no', 'false'
    false
  end
end

def log(str, color_mode, color_fg = nil, color_bg = nil, bold = nil)
  use_color = color_mode == 'always' || (color_mode == 'auto' && !IS_WINDOWS)
  s = String.new('')
  s << "\e[1m" if use_color && bold
  s << "\e[3#{color_fg}m" if use_color && color_fg
  s << "\e[4#{color_bg}m" if use_color && color_bg
  s << str
  s << "\e[0m" if use_color && (bold || color_fg)
  warn s
end

def log_info(str, config)
  return unless config['verbose']
  log("[houcluttex] info: #{str}", config['color'] || 'auto', 2)
end

def log_warn(str, config)
  log("[houcluttex] warn: #{str}", config['color'] || 'auto', 3, nil, true)
end

def log_error(str, config)
  log("[houcluttex] error: #{str}", config['color'] || 'auto', 1, nil, true)
end

def version
  require 'houcluttex/version'
  puts "houcluttex v#{Houcluttex::VERSION}"
  exit
end

config_file = %w[houcluttex.yml houcluttex.yaml houcluttex_config.yml houcluttex_config.yaml houcluttexrc .houcluttexrc].find{|e| File.exist?(e)}

# parse command-line options

argv = ARGV.dup
config_by_args = {}
remain_args = []
ignored_args = []

until argv.empty?
  arg = argv.shift
  if arg == '--'
    remain_args += argv
    argv = []
  elsif arg.start_with?('--')
    m = arg.match(/\A--([^=]+)(=(.*))?\z/)
    key = m[1]
    value = -> {m[3] || argv.shift}
    case key
    when 'fresh', 'change-directory', 'watch', 'verbose', 'shell-escape', 'shell-restricted', 'file-line-error', 'halt-on-error'
      config_by_args[key] = true
    when 'no-change-directory', 'no-shell-escape', 'no-file-line-error', 'no-halt-on-error'
      config_by_args[key[3..-1]] = false
    when 'tex-options', 'dvipdfmx-options'
      config_by_args[key[0..-2]] ||= []
      config_by_args[key[0..-2]] += value[].shellsplit
    when 'tex-option', 'dvipdfmx-option'
      config_by_args[key] ||= []
      config_by_args[key] << value[]
    when 'includeonly', 'package-support'
      config_by_args[key] = value[].split(',')
    when 'color'
      config_by_args[key] = m[3] || 'always'
    when 'input'
      ignored_args << arg
      value[]
    when 'config'
      config_file = value[]
    when 'version'
      version
    when 'cluttex-path', 'engine', 'output', 'max-iterations', 'make-depends', 'engine-executable', 'makeindex', 'bibtex', 'biber', 'makeglossaries', 'synctex', 'interaction', 'jobname', 'fmt', 'output-directory', 'output-format'
      config_by_args[key] = value[]
    else
      ignored_args << arg
    end
  elsif arg.start_with?('-')
    key = arg[1..-1]
    case key
    when 'e'
      config_by_args['engine'] = argv.shift
    when 'o'
      config_by_args['output'] = argv.shift
    when 'v'
      version
    when 'V'
      config_by_args['verbose'] = true
    when 'shell-escape', 'shell-restricted', 'file-line-error', 'halt-on-error'
      config_by_args[key] = true
    when 'no-shell-escape', 'no-file-line-error', 'no-halt-on-error'
      config_by_args[key[3..-1]] = false
    when 'synctex', 'interaction', 'jobname', 'fmt', 'output-directory', 'output-format'
      config_by_args[key] = argv.shift
    else
      ignored_args << arg
    end
  else
    remain_args << arg
  end
end

# load yaml
config = config_file ? YAML.load_file(config_file) : {}

# decide input file
if remain_args.size >= 2
  log_error('multiple input files', config)
  exit 1
end

config['input'] = remain_args[0] unless remain_args.empty?
unless config['input']
  log_error('no input file', config)
  exit 1
end

# parse magic comments

loop do
  log_info("input file: #{config['input']}", config)
  raise "input file `#{config['input']}` does not exist" unless File.exist?(config['input'])

  root_file = nil
  File.open(config['input'], external_encoding: 'utf-8') do |io|
    io.each do |line|
      next if line.strip.empty?
      break unless line[0] == '%'
      m = line.match(/^%\s*!TEX (\S+)\s*=\s*(.*?)\s*$/)
      next unless m
      key = m[1].tr('_-', '').downcase
      value = m[2]
      case key
      when 'root'
        root_file = value
      when 'engine', 'synctex', 'jobname', 'makeindex', 'bibtex'
        config[key] = value
      when 'program'
        config['engine'] = value
      when 'format', 'outputformat'
        config['output-format'] = value
      when 'outputdirectory'
        config['output-directory'] = value
      when 'enablesynctex'
        value = convert_bool(value)
        raise 'magic option `enableSynctex` must be boolean' if value.nil?
        config['synctex'] = value ? (config['synctex'] || 1) : nil
      when 'enableshellescape'
        value = convert_bool(value)
        raise 'magic option `enableShellEscape` must be boolean' if value.nil?
        config['shell-escape'] = value
      else
        log_warn("magic comment `#{m[1]}` is ignored", config)
      end
    end
  end
  break if root_file.nil? || config['input'] == root_file
  config['input'] = root_file
end

# merge config
config.merge!(config_by_args)

log_warn("option #{ignored_args.map{|e| "`#{e}`"}.join(', ')} is ignored", config) unless ignored_args.empty?

# specify command
config['cluttex-path'] ||= 'cluttex'
`type #{config['cluttex-path']} 2>&1`
raise "command `#{config['cluttex-path']}` not found" unless $?.success?

log_info("configurations: #{config.inspect}", config)

# generate command

cmd_args = []

config.each do |k, v|
  next if v.nil?
  case k
  when 'cluttex-path', 'input'
    nil
  when 'tex-option', 'dvipdfmx-option'
    v.each{|e| cmd_args << "--#{k}=#{e}"} unless v.empty?
  when 'includeonly', 'package-support'
    cmd_args << (v.is_a?(Array) ? "--#{k}=#{v.join(',')}" : "--#{k}=#{v}") unless v.empty?
  when 'fresh', 'watch', 'verbose', 'shell-restricted'
    cmd_args << "--#{k}" if v
  when 'change-directory', 'shell-escape', 'file-line-error', 'halt-on-error'
    cmd_args << (v ? "--#{k}" : "--no-#{k}")
  else
    cmd_args << "--#{k}=#{v}"
  end
end

cmd_args << '--'
cmd_args << config['input']

FileUtils.mkdir_p(config['output-directory']) if config['output-directory']

log_info("args: #{cmd_args.inspect}", config)

system(config['cluttex-path'], *cmd_args)
